# Generated by Django 4.2.7 on 2023-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200)),
                ('Shift', models.CharField(max_length=10)),
            ],
        ),
    ]
