# Generated by Django 4.2.7 on 2023-12-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_rename_teachers_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=50)),
                ('Duaration', models.CharField(max_length=10)),
                ('Fee', models.CharField(max_length=5)),
            ],
        ),
    ]
