# Generated by Django 4.2.7 on 2023-12-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=220)),
                ('Phone', models.CharField(max_length=20)),
                ('Class_Time', models.DateField()),
                ('Course', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('F_Amount', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
