# Generated by Django 4.2.7 on 2023-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_payment_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=220)),
                ('Phone', models.CharField(max_length=10)),
                ('Class_time', models.DateTimeField()),
                ('Date', models.DateField()),
                ('Hardware', models.CharField(max_length=5)),
                ('Multimedia', models.CharField(max_length=10)),
                ('Webdesign', models.CharField(max_length=5)),
                ('Network', models.CharField(max_length=5)),
                ('Database', models.CharField(max_length=5)),
                ('Programming', models.CharField(max_length=5)),
                ('Thesis_Book', models.CharField(max_length=5)),
                ('Total', models.FloatField()),
                ('Average', models.FloatField()),
                ('Grade', models.CharField(max_length=2)),
            ],
        ),
    ]
