# Generated by Django 4.2.7 on 2023-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Class_Time',
            field=models.DateTimeField(),
        ),
    ]
