# Generated by Django 4.2.7 on 2024-01-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_alter_payment_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='Class_time',
            field=models.TimeField(),
        ),
    ]
