# Generated by Django 4.2.7 on 2024-01-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_alter_exams_class_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Course', models.CharField(max_length=100)),
                ('Time', models.TimeField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Payment_Mode', models.CharField(max_length=5)),
                ('date', models.DateField()),
            ],
        ),
    ]
