# Generated by Django 4.2.7 on 2024-03-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_customuser_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
