# Generated by Django 4.2.7 on 2024-03-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Class_Time',
            field=models.TimeField(),
        ),
    ]
